version: '3'
services:
  nr_ue:
    #image: docker_ueransim
    build: ./ueransim
    container_name: nr_ue
    stdin_open: true
    tty: true
    volumes:
      - ./li/pyli5:/mnt/li/pyli5
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-ue-1
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_UE_IP}
networks:
  default:
    external:
      name: docker_open5gs_default
